
version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file userHandler.yaml leagueHandler.yaml --s3-bucket leaguemanagement 
                                   --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - leagueHandler.yaml
    - userHandler.yaml
    - outputSamTemplate.yaml
