AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  leagueHandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::009394877865:role/service-role/damcoApi'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: '/league/{proxy+}'
            Method: ANY
        Api2:
          Type: Api
          Properties:
            Path: /league
            Method: ANY
